---
abstract: 'API Rest backend'
author:
  - 'Lucas Tiago de Moraes <lucastiagodemoraes@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Minion: '0'
  Mojolicious: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Minion-Backend-API
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Minion: '0'
  Mojolicious: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/lucas1/Minion-Backend-API/issues
  homepage: https://github.com/lucas1/Minion-Backend-API
  repository: https://github.com/lucas1/Minion-Backend-API
version: 0.02
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
